# Generated by Django 3.2.6 on 2021-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, help_text='nechanchi sinf', max_length=222),
        ),
    ]
