# Generated by Django 3.2.6 on 2021-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=222)),
                ('surname', models.CharField(blank=True, max_length=222)),
                ('lastname', models.CharField(blank=True, max_length=222)),
                ('subject', models.CharField(blank=True, max_length=222)),
                ('level', models.CharField(blank=True, choices=[('Director', 'Direktor'), ('Zauch', 'Zauch'), ('Zamdirektor', 'Zamdirektor'), ('Zavhoz', 'Zavhoz')], max_length=222)),
                ('level_years', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('classes', models.CharField(blank=True, choices=[('1 a', '1 a'), ('1 b', '1 b'), ('1 v', '1 v'), ('1 g', '1 g'), ('2 a', '2 a'), ('2 b', '2 b'), ('2 v', '2 v'), ('2 g', '2 g')], max_length=222)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
